spring.application.name=esientradas

#Comunicación con ESIUSUARIOS
esiusuarios.base-url=${ESIUSUARIOS_URL}
esiusuarios.api-key=${API_KEY_ESIUSUARIOS}

#CONFIGURACIÓN DE STRIPE
stripe.api-key=${STRIPE_KEY}

#CONFIGURACIÓN DE CORREO
correo.username=${GMAIL_ACC}
correo.password=${GMAIL_PSWD}

#CONFIGURACIÓN DE BASE DE DATOS
spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PSWD}

# Configuración de Hibernate para MySQL
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view = false
server.error.include-message=always

# --- Configuración para mantener la terminal limpia ---
spring.jpa.properties.hibernate.generate_statistics=false
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR